version: '3'

services:
  backend:
    image: backend:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_backend$
    volumes:
      - C:\Users\Brian\Documents\GitHub\novelmate\Backend\Backend:/app
      - C:\Users\Brian\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_backend$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_backend$ bin/MCD/Debug/netcoreapp2.0/NovelMate.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
